# Generated by Django 3.1.2 on 2021-01-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_car', to='api.city', verbose_name='City'),
        ),
    ]
