# Generated by Django 3.1.2 on 2021-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210118_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='models'),
        ),
    ]
